site_name: kafka 设计实现解析
site_url: https://mapan1984.github.io/kafka-design/
repo_url: https://github.com/mapan1984/kafka-design/
site_description: kafka 设计实现解析
site_author: mapan

nav:
  - '0. kafka 设计实现解析': 'README.md'
  - 1. server 解析:
    - '1-server 解析/README.md'
    - 1.1 server 启动过程: '1-server 解析/1-server 启动过程.md'
    - 1.2 server 网络模型: '1-server 解析/2-server 网络模型.md'
    - 1.3 KafkaController:
      - '1-server 解析/3-KafkaController/README.md'
      - 1.3.1 KafkaController 启动: '1-server 解析/3-KafkaController/1-controller启动.md'
      - 1.3.2 KafkaController 组件:
        - '1-server 解析/3-KafkaController/2-controller组件/README.md'
        - 1.3.2.1 ControllerContext: '1-server 解析/3-KafkaController/2-controller组件/1-ControllerContext.md'
        - 1.3.2.2 ReplicaStateMachine: '1-server 解析/3-KafkaController/2-controller组件/2-ReplicaStateMachine.md'
        - 1.3.2.3 PartitionStateMachine: '1-server 解析/3-KafkaController/2-controller组件/3-PartitionStateMachine.md'
        - 1.3.2.4 ControllerChannelManager: '1-server 解析/3-KafkaController/2-controller组件/4-ControllerChannelManager.md'
      - 1.3.3 reassign partitions: '1-server 解析/3-KafkaController/3-reassign-partitions.md'
      - 1.3.4 delete topic: '1-server 解析/3-KafkaController/4-delete-topic.md'
    - 1.4 ReplicaManager:
      - '1-server 解析/4-ReplicaManager/README.md'
      - 1.4.1 ReplicaManager 启动: '1-server 解析/4-ReplicaManager/1-replica manager 启动.md'
      - 1.4.2 isr: '1-server 解析/4-ReplicaManager/2-isr.md'
      - 1.4.3 become leader or follower: '1-server 解析/4-ReplicaManager/3-become-leader-or-follower.md'
      - 1.4.4 replica fetcher manager: '1-server 解析/4-ReplicaManager/4-replica-fetcher-manager.md'
      - 1.4.7 append records: '1-server 解析/4-ReplicaManager/7-append-records.md'
      - 1.4.8 delete records: '1-server 解析/4-ReplicaManager/8-delete-records.md'
      - 1.4.8 replication quota manager: '1-server 解析/4-ReplicaManager/9-replication-quota-manager.md'
    - 1.5 GroupCoordinator:
      - '1-server 解析/5-GroupCoordinator/README.md'
      - 1.5.1 coordinator 启动: '1-server 解析/5-GroupCoordinator/1-coordinator启动.md'
      - 1.5.2 coordinator 切换及更新: '1-server 解析/5-GroupCoordinator/2-coordinator切换及更新.md'
    - 1.6 LogManager:
      - '1-server 解析/6-LogManager/README.md'
      - 1.6.1 LogManager 启动: '1-server 解析/6-LogManager/1-LogManager 启动.md'
      - 1.6.2 日志清理: '1-server 解析/6-LogManager/2-日志清理.md'
      - 1.6.3 flush log: '1-server 解析/6-LogManager/3-flush log.md'
      - 1.6.4 recovery point: '1-server 解析/6-LogManager/4-recovery-point.md'
      - 1.6.5 start offset: '1-server 解析/6-LogManager/5-start-offset.md'
      - 1.6.7 压缩策略的日志清理: '1-server 解析/6-LogManager/7-压缩策略的日志清理.md'
      - 1.6.8 LogSegment: '1-server 解析/6-LogManager/8-LogSegment.md'
    - 1.7 Acl 权限控制: '1-server 解析/7-acl 控制/README.md'
    - 1.9 Metrics:
      - '1-server 解析/9-Metrics/README.md'
      - 1.9.1 Yammer: '1-server 解析/9-Metrics/1-Yammer.md'
      - 1.9.2 Kafka Metrics Group: '1-server 解析/9-Metrics/2-KafkaMetricsGroup.md'
    - 1.10 Config:
      - '1-server 解析/10-Config/README.md'
      - 1.10.1 Kafka Config: '1-server 解析/10-Config/1-KafkaConfig.md'
      - 1.10.2 Dynamic Config: '1-server 解析/10-Config/2-Dynamic-Config.md'
  - 2. producer 解析:
    - '2-producer 解析/README.md'
    - 2.1 producer 发送消息: '2-producer 解析/1-producer 发送消息.md'
    - 2.2 producer 幂等性: '2-producer 解析/2-producer 幂等性.md'
    - 2.3 producer 加密/认证: '2-producer 解析/3-producer 加密 认证.md'
  - 3. consumer 解析:
    - '3-consumer 解析/README.md'
    - 3.1-消费组管理: '3-consumer 解析/1-消费组管理.md'
    - 3.2-拉取消息: '3-consumer 解析/2-consumer 拉取消息.md'
  - 4. kafka network io:
    - '4-kafka-network-io/README.md'
    - 4.1 KafkaChannel: '4-kafka-network-io/1-KafkaChannel.md'
    - 4.2 TransportLayer: '4-kafka-network-io/2-TransportLayer.md'
    - 4.3 Authenticator: '4-kafka-network-io/3-Authenticator.md'
  - 5. Release Note:
    - '5-release note/README.md'
    - 2.7: '5-release note/2.7.md'
    - 2.8.0: '5-release note/2.8.0.md'
  - 6. Src:
    - '6-src/README.md'
    - Clients:
      - Clients:
        - Producer:
          - Internals:
            - Producer Batch: '6-src/clients/clients/producer/internals/ProducerBatch.md'
            - Producer Metadata: '6-src/clients/clients/producer/internals/ProducerMetadata.md'
            - Record Accumulator: '6-src/clients/clients/producer/internals/RecordAccumulator.md'
            - Sender: '6-src/clients/clients/producer/internals/Sender.md'
          - Kafka Producer: '6-src/clients/clients/producer/KafkaProducer.md'
        - Metadata: '6-src/clients/clients/Metadata.md'
        - Network Client: '6-src/clients/clients/NetworkClient.md'
      - Common:
        - Network:
          - Kafka Channel: '6-src/clients/common/network/KafkaChannel.md'
          - Network Receive: '6-src/clients/common/network/NetworkReceive.md'
          - Network Send: '6-src/clients/common/network/NetworkSend.md'
          - Receive: '6-src/clients/common/network/Receive.md'
          - Selector: '6-src/clients/common/network/Selector.md'
          - Send: '6-src/clients/common/network/Send.md'
          - Transport Layer: '6-src/clients/common/network/TransportLayer.md'
        - Utils:
          - Kafka Thread: '6-src/clients/common/utils/KafkaThread.md'
    - Core:
      - Kafka:
        - '6-src/core/kafka/README.md'
        - Controller:
          - ControllerState: '6-src/core/kafka/controller/ControllerState.md'
          - ReplicaStateMachine: '6-src/core/kafka/controller/ReplicaStateMachine.md'
          - ControllerContext:
            - '6-src/core/kafka/controller/ControllerContext/README.md'
            - ReplicaAssignment: '6-src/core/kafka/controller/ControllerContext/ReplicaAssignment.md'
          - ControllerEventManager:
            - '6-src/core/kafka/controller/ControllerEventManager/README.md'
            - ControllerEventProcessor: '6-src/core/kafka/controller/ControllerEventManager/ControllerEventProcessor.md'
            - ControllerEventThread: '6-src/core/kafka/controller/ControllerEventManager/ControllerEventThread.md'
            - QueueEvent: '6-src/core/kafka/controller/ControllerEventManager/QueueEvent.md'
          - KafkaController:
            - '6-src/core/kafka/controller/KafkaController/README.md'
            - ControllerEvent: '6-src/core/kafka/controller/KafkaController/ControllerEvent.md'
        - Network:
          - Socket Server:
            - '6-src/core/kafka/network/SocketServer/README.md'
            - Acceptor: '6-src/core/kafka/network/SocketServer/Acceptor.md'
            - Processor: '6-src/core/kafka/network/SocketServer/Processor.md'
          - Request Channel: '6-src/core/kafka/network/RequestChannel.md'
        - Server:
          - Kafka Request Handler:
            - '6-src/core/kafka/server/KafkaRequestHandler/README.md'
            - Kafka Request Handler Pool: '6-src/core/kafka/server/KafkaRequestHandler/KafkaRequestHandlerPool.md'
          - Kafka Apis: '6-src/core/kafka/server/KafkaApis.md'
          - Kafka Server: '6-src/core/kafka/server/KafkaServer.md'
        - Utils:
          - Kafka Scheduler: '6-src/core/kafka/utils/KafkaScheduler.md'
  - 7. 其他:
    - 7.1 topic 名规则: '7-other/1-topic-name-limit.md'
    - 7.2 page cache: '7-other/2-kafka-page-cache.md'
    - 7.3 reassign partition: '7-other/3-reassign-partition.md'

# docs_dir: docs

theme:
  # name: readthedocs
  name: material
  language: 'zh'
  # palette:
  #   scheme: slate
  #   primary: blue grey
  #   accent: deep orange
  palette:
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - section-index
  - search:
      lang:
        - en
        - ja

extra_css: []


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
